### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zivanfi** [cddmp/usblock#1]
Hi,

This looks like a useful lightweight utility, but the conditions of using and potentially modifying it are not specified. Could you please add a license file to the project?

Thanks,

Zoltan

**Comment by cddmp** [comment]
Hi zivanfi,

sry for being late and thanks for your request. I've added a license now.

If you want to play with the tool, you could try also the version in the dev branch. I would be interested if it works for you as well.
The code in the master branch has one downside. Though it is much simpler, it does not handle USB devices correctly, which have multiple configurations and  uses configurations ids which don't start at 0 (a very weird thing with USB, not sure why it was implemented like that). I came across this behaviour with a USB device and have fixed that some months ago with the dev branch. Unfortunately that made the code a bit more complicated.

Thanks for playing with it! :)

**Comment by cddmp** [comment]
Will close this. If there are any open questions, just add a comment!
